export const TRENDING_NAMES = [
  "Taylor Swift",
  "Zendaya",
  "Tom Holland",
  "Brad Pitt",
  "Angelina Jolie",
  "Jennifer Lopez",
  "Ben Affleck",
  "Leonardo DiCaprio",
  "Selena Gomez",
  "Justin Bieber",
  "Ariana Grande",
  "Harry Styles",
  "Timothee Chalamet",
  "Kylie Jenner",
  "Kim Kardashian",
  "Pete Davidson",
  "Travis Kelce",
  "Rihanna",
  "A$AP Rocky",
  "Ryan Reynolds",
  "Blake Lively",
  "Miley Cyrus",
  "Johnny Depp",
  "Zayn Malik",
  "Gigi Hadid",
  "Kendall Jenner",
  "Drake",
  "The Weeknd",
];
